version: '3'
services:
  bank:
    build: .
    container_name: bank
    ports:
      - "50055:50055"
    networks:
      - my_network


  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    container_name: dbBANK
    ports:
      - "5434:5432"
    networks:
      - my_network

networks:
  my_network:
    external: true
