version: '3.9'
services:
  web:
    build: .
    container_name: auth
    ports:
      - "50051:50051"
    networks:
      - my_network
networks:
  my_network:
    external: true

#  prometheus:
#    image: prom/prometheus:latest
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#
#  grafana:
#    image: windblows123/grafana:1.0.0
#    ports:
#      - "3000:3000"
#    volumes:
#      - grafana-storage:/var/lib/grafana
#      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
#
#
#volumes:
#  grafana-storage:

