version: '3'
services:
  user:
    build: .
    container_name: user
    ports:
      - "50052:50052"
    networks:
      - my_network


  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    container_name: db
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:
    external: true
