name: Create Pull Request

on:
  push:
    branches:
      - main  # Здесь укажите ветку, на которую хотите реагировать

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create a new branch
        run: |
          git checkout -b "pr-branch-${{ github.sha }}"
          git push -u origin "pr-branch-${{ github.sha }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto PR for commit ${{ github.sha }}"
          branch: "pr-branch-${{ github.sha }}"
          base: main
          title: "Auto PR for commit ${{ github.sha }}"
          body: "This pull request is automatically created for commit ${{ github.sha }}"
